services:
  - type: web
    name: sistema-emprestimo
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: sql112.infinityfree.com
      - key: DB_USER
        value: if0_38382553
      - key: DB_PASSWORD
        value: JtPMCeYshtuNW8x
      - key: DB_NAME
        value: if0_38382553
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001 